# LCF-A
python cfcc.py --name-exp=exp_LCFA_t1 --image-size=200 --intermediate-blocks=0 --pool-size=1 --W-last=1 --W=3 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=9 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 2 3 --valid-sets 2 3 --test-sets 1 > exp_LCFA_t1.log
python cfcc.py --name-exp=exp_LCFA_t2 --image-size=200 --intermediate-blocks=0 --pool-size=1 --W-last=1 --W=3 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=9 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 1 3 --valid-sets 1 3 --test-sets 2 > exp_LCFA_t2.log
python cfcc.py --name-exp=exp_LCFA_t3 --image-size=200 --intermediate-blocks=0 --pool-size=1 --W-last=1 --W=3 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=9 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 1 2 --valid-sets 1 2 --test-sets 3 > exp_LCFA_t3.log

# ECF-A
python cfcc.py --name-exp=exp_ECFA_t1 --image-size=200 --intermediate-blocks=1 --pool-size=1 --W-last=1 --W=3 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=9 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 2 3 --valid-sets 2 3 --test-sets 1 > exp_ECFA_t1.log
python cfcc.py --name-exp=exp_ECFA_t2 --image-size=200 --intermediate-blocks=1 --pool-size=1 --W-last=1 --W=3 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=9 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 1 3 --valid-sets 1 3 --test-sets 2 > exp_ECFA_t2.log
python cfcc.py --name-exp=exp_ECFA_t3 --image-size=200 --intermediate-blocks=1 --pool-size=1 --W-last=1 --W=3 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=9 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 1 2 --valid-sets 1 2 --test-sets 3 > exp_ECFA_t3.log

# ECF-B
python cfcc.py --name-exp=exp_ECFB_t1 --image-size=200 --batch-size=8 --intermediate-blocks=1 --pool-size=3 --W-last=2 --W=5 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=27 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 2 3 --valid-sets 2 3 --test-sets 1 > exp_ECFB_t1.log
python cfcc.py --name-exp=exp_ECFB_t2 --image-size=200 --batch-size=8 --intermediate-blocks=1 --pool-size=3 --W-last=2 --W=5 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=27 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 1 3 --valid-sets 1 3 --test-sets 2 > exp_ECFB_t2.log
python cfcc.py --name-exp=exp_ECFB_t3 --image-size=200 --batch-size=8 --intermediate-blocks=1 --pool-size=3 --W-last=2 --W=5 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=27 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 1 2 --valid-sets 1 2 --test-sets 3 > exp_ECFB_t3.log
