# LCF-A
python cfcc.py --name-exp=exp101L1_LCFbase_r1_t1_e1k --image-size=200 --intermediate-blocks=0 --pool-size=1 --W-last=1 --W=3 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=9 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 2 3 --valid-sets 2 3 --test-sets 1 > exp101L1_LCFbase_r1_t1_e1k.log
python cfcc.py --name-exp=exp101L1_LCFbase_r1_t2_e1k --image-size=200 --intermediate-blocks=0 --pool-size=1 --W-last=1 --W=3 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=9 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 1 3 --valid-sets 1 3 --test-sets 2 > exp101L1_LCFbase_r1_t2_e1k.log
python cfcc.py --name-exp=exp101L1_LCFbase_r1_t3_e1k --image-size=200 --intermediate-blocks=0 --pool-size=1 --W-last=1 --W=3 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=9 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 1 2 --valid-sets 1 2 --test-sets 3 > exp101L1_LCFbase_r1_t3_e1k.log

# ECF-A
python cfcc.py --name-exp=exp101L1_ECFbase_r1_t1_e1k --image-size=200 --intermediate-blocks=1 --pool-size=1 --W-last=1 --W=3 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=9 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 2 3 --valid-sets 2 3 --test-sets 1 > exp101L1_ECFbase_r1_t1_e1k.log
python cfcc.py --name-exp=exp101L1_ECFbase_r1_t2_e1k --image-size=200 --intermediate-blocks=1 --pool-size=1 --W-last=1 --W=3 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=9 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 1 3 --valid-sets 1 3 --test-sets 2 > exp101L1_ECFbase_r1_t2_e1k.log
python cfcc.py --name-exp=exp101L1_ECFbase_r1_t3_e1k --image-size=200 --intermediate-blocks=1 --pool-size=1 --W-last=1 --W=3 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=9 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 1 2 --valid-sets 1 2 --test-sets 3 > exp101L1_ECFbase_r1_t3_e1k.log

# ECF-B
python cfcc.py --name-exp=exp101L1_ECFswept_r1_t1_e1k --image-size=200 --batch-size=8 --intermediate-blocks=1 --pool-size=3 --W-last=2 --W=5 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=27 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 2 3 --valid-sets 2 3 --test-sets 1 > exp101L1_ECFswept_r1_t1_e1k.log
python cfcc.py --name-exp=exp101L1_ECFswept_r1_t2_e1k --image-size=200 --batch-size=8 --intermediate-blocks=1 --pool-size=3 --W-last=2 --W=5 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=27 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 1 3 --valid-sets 1 3 --test-sets 2 > exp101L1_ECFswept_r1_t2_e1k.log
python cfcc.py --name-exp=exp101L1_ECFswept_r1_t3_e1k --image-size=200 --batch-size=8 --intermediate-blocks=1 --pool-size=3 --W-last=2 --W=5 --sigma=-1 --test-sets=1 --save-output --njet=1 --inner-size=27 --mink-norm=1.000001 --epochs=1000 --njet-protection1=prelu --nl=prelu --njet-protection2=posrelu --mink-protection-pow=oneabs --validation-transform=isotropic --data-augmentation --train-sets 1 2 --valid-sets 1 2 --test-sets 3 > exp101L1_ECFswept_r1_t3_e1k.log
